version: '3.9'

services:
  web:
    image:
      weather:latest
    build: ./
    command: >
      sh -c "gunicorn weather_forecast.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    container_name: weather
    restart: "always"