# Generated by Django 5.0.7 on 2024-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImpressionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=255, unique=True)),
                ("impressions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Статистика показов",
                "verbose_name_plural": "Статистики показов",
            },
        ),
    ]
